# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NhqF7kYaRFb23hacXWfZ0Yp7Jyz-e9-0
"""

import pandas as pd
titanic=pd. read_csv("/content/Titanic-Dataset.csv")
print(titanic)

filtr=titanic[titanic["Age"] >19]
print(filtr)

kimdir=titanic[titanic["Name"]=="Braund, Mr. Owen Harris"]
kimdir=titanic[titanic["Name"]=="Braund, Mr. Owen Harris"]
print(kimdirkimdir)